from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('default_currency', models.CharField(default='USD', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('ingestion_mode', models.CharField(choices=[('csv_upload', 'CSV Upload'), ('api_pull', 'API Pull'), ('manual', 'Manual Paste')], default='csv_upload', max_length=20)),
                ('system_of_record', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('plant_code', models.CharField(blank=True, max_length=80)),
                ('meter_id', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_format', models.CharField(default='csv', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('imported_by_email', models.EmailField(blank=True, max_length=254)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin')], default='analyst', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'email')},
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('source_record_key', models.CharField(blank=True, max_length=120)),
                ('row_hash', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('ingested', 'Ingested'), ('failed', 'Failed')], default='ingested', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.organization')),
            ],
            options={
                'unique_together': {('import_batch', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_unit', models.CharField(max_length=40)),
                ('to_unit', models.CharField(max_length=40)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('domain', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactorReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=40)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('factor_unit', models.CharField(default='kgCO2e', max_length=40)),
                ('scope_category', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=4)),
                ('source_system', models.CharField(blank=True, max_length=80)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(max_length=80)),
                ('source_record_key', models.CharField(blank=True, max_length=120)),
                ('activity_type', models.CharField(max_length=80)),
                ('scope_category', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=4)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=40)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=40)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emissions_kg_co2e', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('suspicious_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('suspicious_flags', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('edited_by_email', models.EmailField(blank=True, max_length=254)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.datasource')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.organization')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_record', to='core.rawrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('before_payload', models.JSONField(default=dict)),
                ('after_payload', models.JSONField(default=dict)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.normalizedemissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization')),
            ],
        ),
    ]
